### ISSUE TITLE
GreatFET logic configurations

### ISSUE THREAD

**Issue by dominicgs** [dominicgs/GreatFET-experimental#209]
The logic analyser function currently supports one clock rate and 8 pin sampling.  It would be nice to support lower clock rates for host software that wants to consume data more slowly.

It would also be nice to push the rate higher for fewer pins, e.g. 4 pin @ 100 MHz or 2 pin @ 200 MHz

**Comment by mossmann** [comment]
implemented in 8c2c0d9
