### ISSUE TITLE
where is the pc software for greatfet

### ISSUE THREAD

**Issue by wanming2008** [dominicgs/GreatFET-experimental#27]
hi  dominicgs 
i have made one greatfet myself but i can not find the pc software in
github，in greatfet repository  or this repository。 i tried  usb goodfet PC python software whrited by  goodsman。but it seems not work。PC can not comincation with greatfet。 can you tell me where i can download the pc python software for greatfet。

**Comment by dominicgs** [comment]
There's some experimental code in this repository: https://github.com/dominicgs/GreatFET-experimental/tree/master/host
